"""Inference engine for speech-to-text transcription.

Supports three modes:
- 'nemo': NVIDIA Parakeet TDT via NeMo (requires CUDA)
- 'mlx': Whisper via mlx-whisper (requires Apple Silicon)
- 'mock': Deterministic mock for testing (no hardware required)
"""

from __future__ import annotations

import asyncio
import logging
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass

from parakey_backend.config import BackendConfig

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class EngineEvent:
    """An event generated by the inference engine."""

    kind: str  # 'partial', 'final', 'status', 'error'
    text: str
    stability: float | None = None


def generate_mock_events(
    config: BackendConfig,
    audio_frames: list[bytes],
) -> list[EngineEvent]:
    """Generate deterministic mock events for testing.

    Emits one partial event every ``config.partial_every_n_frames`` frames,
    then a final event with ``config.final_text``.
    """
    events: list[EngineEvent] = []

    for i, _ in enumerate(audio_frames, 1):
        if config.partial_every_n_frames > 0 and i % config.partial_every_n_frames == 0:
            events.append(
                EngineEvent(
                    kind="partial",
                    text=f"Partial {i // config.partial_every_n_frames}...",
                    stability=0.7,
                )
            )

    events.append(EngineEvent(kind="final", text=config.final_text))
    return events


class MockInferenceEngine:
    """Deterministic mock engine for unit tests — no hardware required."""

    def __init__(self, config: BackendConfig) -> None:
        self._config = config
        self._loaded = False

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    @property
    def device(self) -> str:
        return "mock"

    def load_model(self) -> None:
        self._loaded = True
        logger.info("Mock engine loaded")

    def unload_model(self) -> None:
        self._loaded = False
        logger.info("Mock engine unloaded")

    async def transcribe(self, audio_data: bytes, sample_rate: int = 16000) -> str:
        if not self._loaded:
            raise RuntimeError("Model not loaded - call load_model() first")
        return self._config.final_text

    async def process_audio_stream(
        self,
        audio_frames: list[bytes],
        sample_rate: int = 16000,
    ) -> list[EngineEvent]:
        if not self._loaded:
            raise RuntimeError("Model not loaded")
        return generate_mock_events(self._config, audio_frames)


class InferenceEngine:
    """NeMo Parakeet TDT engine — requires CUDA."""

    def __init__(self, config: BackendConfig) -> None:
        self._config = config
        self._model_loader = None
        self._executor = ThreadPoolExecutor(max_workers=1)
        self._loaded = False

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    @property
    def device(self) -> str:
        if self._model_loader:
            return self._model_loader.device
        return "unknown"

    def load_model(self) -> None:
        if self._loaded:
            logger.info("Model already loaded")
            return

        try:
            from parakey_backend.model import ModelLoader

            self._model_loader = ModelLoader(
                model_name=self._config.model_name,
                device=self._config.device,
            )
            self._model_loader.load()
            self._loaded = True
            logger.info(f"Inference engine ready on {self._model_loader.device}")

        except Exception as e:
            logger.error(f"Failed to load model: {e}")
            raise

    def unload_model(self) -> None:
        if self._model_loader:
            self._model_loader.unload()
            self._model_loader = None
        self._loaded = False
        logger.info("Model unloaded")

    def _transcribe_sync(self, audio_data: bytes, sample_rate: int) -> str:
        if not self._loaded or self._model_loader is None:
            raise RuntimeError("Model not loaded")
        return self._model_loader.transcribe(audio_data, sample_rate)

    async def transcribe(self, audio_data: bytes, sample_rate: int = 16000) -> str:
        if not self._loaded:
            raise RuntimeError("Model not loaded - call load_model() first")
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            self._executor,
            self._transcribe_sync,
            audio_data,
            sample_rate,
        )

    async def process_audio_stream(
        self,
        audio_frames: list[bytes],
        sample_rate: int = 16000,
    ) -> list[EngineEvent]:
        events: list[EngineEvent] = []
        audio_data = b"".join(audio_frames)

        if len(audio_data) == 0:
            events.append(EngineEvent(kind="final", text=""))
            return events

        events.append(EngineEvent(kind="status", text="Transcribing..."))

        try:
            transcript = await self.transcribe(audio_data, sample_rate)
            events.append(EngineEvent(kind="final", text=transcript.strip()))

        except RuntimeError as e:
            error_str = str(e).lower()
            if "cuda" in error_str and ("out of memory" in error_str or "oom" in error_str):
                logger.error("CUDA out of memory during transcription")
                events.append(EngineEvent(kind="error", text="Transcription failed: CUDA out of memory"))
            else:
                logger.error(f"Transcription failed: {e}")
                events.append(EngineEvent(kind="error", text=f"Transcription failed: {e}"))

        except Exception as e:
            logger.error(f"Transcription failed: {e}")
            events.append(EngineEvent(kind="error", text=f"Transcription failed: {e}"))

        return events


class MLXInferenceEngine:
    """MLX Whisper engine — requires Apple Silicon (macOS 13.3+)."""

    def __init__(self, config: BackendConfig) -> None:
        self._config = config
        self._model_loader = None
        self._executor = ThreadPoolExecutor(max_workers=1)
        self._loaded = False

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    @property
    def device(self) -> str:
        return "mlx"

    def load_model(self) -> None:
        if self._loaded:
            logger.info("MLX model already loaded")
            return

        try:
            from parakey_backend.model import MLXModelLoader

            self._model_loader = MLXModelLoader(model_name=self._config.model_name)
            self._model_loader.load()
            self._loaded = True
            logger.info("MLX inference engine ready")

        except Exception as e:
            logger.error(f"Failed to load MLX model: {e}")
            raise

    def unload_model(self) -> None:
        if self._model_loader:
            self._model_loader.unload()
            self._model_loader = None
        self._loaded = False
        logger.info("MLX model unloaded")

    def _transcribe_sync(self, audio_data: bytes, sample_rate: int) -> str:
        if not self._loaded or self._model_loader is None:
            raise RuntimeError("Model not loaded")
        return self._model_loader.transcribe(audio_data, sample_rate)

    async def transcribe(self, audio_data: bytes, sample_rate: int = 16000) -> str:
        if not self._loaded:
            raise RuntimeError("Model not loaded - call load_model() first")
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            self._executor,
            self._transcribe_sync,
            audio_data,
            sample_rate,
        )

    async def process_audio_stream(
        self,
        audio_frames: list[bytes],
        sample_rate: int = 16000,
    ) -> list[EngineEvent]:
        events: list[EngineEvent] = []
        audio_data = b"".join(audio_frames)

        if len(audio_data) == 0:
            events.append(EngineEvent(kind="final", text=""))
            return events

        events.append(EngineEvent(kind="status", text="Transcribing..."))

        try:
            transcript = await self.transcribe(audio_data, sample_rate)
            events.append(EngineEvent(kind="final", text=transcript.strip()))

        except Exception as e:
            logger.error(f"MLX transcription failed: {e}")
            events.append(EngineEvent(kind="error", text=f"Transcription failed: {e}"))

        return events


def create_engine(
    config: BackendConfig,
) -> InferenceEngine | MLXInferenceEngine | MockInferenceEngine:
    """Create an inference engine based on the configured mode."""
    if config.mode == "mock":
        return MockInferenceEngine(config)
    if config.mode == "mlx":
        return MLXInferenceEngine(config)
    return InferenceEngine(config)


__all__ = [
    "EngineEvent",
    "InferenceEngine",
    "MLXInferenceEngine",
    "MockInferenceEngine",
    "create_engine",
    "generate_mock_events",
]
